
--DML for dashboard_demo_schema

SET DEFINE OFF;

--DML FOR table dashboard_components

Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,1,'CLV PANEL','PANEL','{ "Title": "CLV, Customer Acquistion & Cross-sell" }', EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,2,'CLV CARD','KPI CARD','{"CARD_HEADER":"CLV","KPIS":[{"KPI_ID":"26","KPI_LBL":"Customer Lifetime Value","KPI_LBL_POSTFIX":"YTD","KPI_PERC_CHANGE":"5%","KPI_PERC_CHANGE_ICON":"upward_arrow","KPI_VALUE":"$22B"}]}', EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,3,'CLV GRAPH','GRAPH_AREA',TO_CLOB(q'[{"xAxis":{"type":"category","boundaryGap":false,"data":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"axisLabel":{"margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisTick":{"show":false}},"yAxis":{"type":"value","axisLabel":{"formatter":"${value}M","margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisLine":{"show":false},"axisTick":{"show":false},"splitLine":{"lineStyle":{"type":"dotted"}}},"grid":{"top":"7%","left":"2%","right":"4%","bottom":"40%","c]')
|| TO_CLOB(q'[ontainLabel":true},"tooltip":{"trigger":"axis","axisPointer":{"type":"line"}},"series":{"data":[9,12,13,9,12,15,9,12,13,9,12,15],"type":"line","areaStyle":{},"smooth":true},"areaStyle":{"color":{"type":"linear","x":0,"y":0,"x2":0,"y2":1,"colorStops":[{"offset":0,"color":"rgba(255, 0, 0, 0.7)"},{"offset":1,"color":"rgba(255, 0, 0, 0)"}],"global":false}}}]'), EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,4,'CLV TOGGLE','TOGGLE','true', EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,5,'CLV TABS','TABS','{ "TAB_LIST": [ { "COMP_ID": "6", "NAME": "Retail" }, { "COMP_ID": "7", "NAME": "AMG" }, { "COMP_ID": "8", "NAME": "C&IB" } ] }', EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,6,'CLV RETAIL CARD','KPI_CARD',TO_CLOB(q'[{"CARD_HEADER":"RETAIL","KPIS":[{ "KPI_LBL": "Total Retail Customers", "KPI_VALUE": "$10.9M", "KPI_PERC_CHANGE": "5%", "KPI_PERC_CHANGE_ICON": "arrow_upward", "KPI_LBL_POSTFIX": "YTD", "KPI_ID": "27" }, { "KPI_LBL": "New Retail Revenue", "KPI_VALUE": "$4.1M", "KPI_PERC_CHANGE": "2%", "KPI_PERC_CHANGE_ICON": "arrow_upward", "KPI_LBL_POSTFIX": "YTD", "KPI_ID": "28" }, { "KPI_LBL": "Cross Retail Revenue", "KPI_VALUE": "$6.8M", "KPI_PERC_CHANGE": "2%", "KPI_PERC_CHANGE_ICON": "arrow_upward", "KPI_LB]')
|| TO_CLOB(q'[L_POSTFIX": "YTD", "KPI_ID": "29" }]}]'), EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,7,'CLV AMG CARD','KPI_CARD',TO_CLOB(q'[{"CARD_HEADER":"AMG","KPIS":[ { "KPI_LBL": "Total AMG Customers", "KPI_VALUE": "$11.8M", "KPI_PERC_CHANGE": "3%", "KPI_PERC_CHANGE_ICON": "arrow_upward", "KPI_LBL_POSTFIX": "YTD", "KPI_ID": "30" }, { "KPI_LBL": "New AMG Customers", "KPI_VALUE": "$3.4M", "KPI_PERC_CHANGE": "4%", "KPI_PERC_CHANGE_ICON": "arrow_upward", "KPI_LBL_POSTFIX": "YTD", "KPI_ID": "31" }, { "KPI_LBL": "Cross AMG Customers", "KPI_VALUE": "$8.4M", "KPI_PERC_CHANGE": "4%", "KPI_PERC_CHANGE_ICON": "arrow_upward", "KPI_LBL_POSTF]')
|| TO_CLOB(q'[IX": "YTD", "KPI_ID": "32" } ]}]'), EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,8,'CLV C&IB CARD','KPI_CARD',TO_CLOB(q'[{"CARD_HEADER":"C&IB","KPIS":[{ "KPI_LBL": "Total C&IB Customers", "KPI_VALUE": "$11M", "KPI_PERC_CHANGE": "4%", "KPI_PERC_CHANGE_ICON": "arrow_upward", "KPI_LBL_POSTFIX": "YTD", "KPI_ID": "33" }, { "KPI_LBL": "New C&IB Customers", "KPI_VALUE": "$6.5M", "KPI_PERC_CHANGE": "2%", "KPI_PERC_CHANGE_ICON": "arrow_upward", "KPI_LBL_POSTFIX": "YTD", "KPI_ID": "34" }, { "KPI_LBL": "Cross C&IB Customers", "KPI_VALUE": "$4.5M", "KPI_PERC_CHANGE": "2%", "KPI_PERC_CHANGE_ICON": "arrow_upward", "KPI_LBL_POST]')
|| TO_CLOB(q'[FIX": "YTD", "KPI_ID": "35" } ]}]'), EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,9,'MARKETING SPEND PANEL','PANEL','{ "Title": "Marketing Spend" }', EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,10,'MARKETING SPEND TABS','TABS','{ "TAB_LIST": [ { "COMP_ID": "11", "NAME": "Retail" }, { "COMP_ID": "12", "NAME": "AMG" }, { "COMP_ID": "13", "NAME": "C&IB" } ] }', EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,11,'MARKETING RETAIL CARD','KPI_CARD','{"CARD_HEADER":"Retail","KPIS":[{"KPI_LBL":"Marketing Spends","KPI_VALUE":"10.3M","KPI_PERC_CHANGE":"3%","KPI_PERC_CHANGE_ICON":"arrow_upward","KPI_LBL_POSTFIX":"YTD","KPI_ID":"36"}]}', EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,12,'MARKETING AMG CARD','KPI_CARD','{"CARD_HEADER":"AMG","KPIS":[{"KPI_LBL":"Marketing Spends","KPI_VALUE":"11.6M","KPI_PERC_CHANGE":"5%","KPI_PERC_CHANGE_ICON":"arrow_upward","KPI_LBL_POSTFIX":"YTD","KPI_ID":"37"}]}', EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,13,'MARKETING CIB CARD','KPI_CARD','{"CARD_HEADER":"AMG","KPIS":[{"KPI_LBL":"Marketing Spends","KPI_VALUE":"13.6M","KPI_PERC_CHANGE":"5%","KPI_PERC_CHANGE_ICON":"arrow_upward","KPI_LBL_POSTFIX":"YTD","KPI_ID":"38"}]}', EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,14,'DIGITAL ACQUISITION PANEL','PANEL','{ "Title": "Digital Acquisition Driven by Marketing" }', EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,15,'DIGITAL ACQUISITION TABS','TABS','{ "TAB_LIST": [ { "COMP_ID": "16", "NAME": "Retail" }, { "COMP_ID": "17", "NAME": "AMG" }, { "COMP_ID": "18", "NAME": "C" } ] }', EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,16,'DIGITAL ACQUISITION RETAIL GRAPH','GRAPH_LINES',TO_CLOB(q'[{"xAxis":{"type":"category","data":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"axisLabel":{"margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisTick":{"show":false}},"yAxis":{"type":"value","axisLabel":{"margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisLine":{"show":false},"axisTick":{"show":false},"splitLine":{"lineStyle":{"type":"dotted"}}},"grid":{"left":"3%","right":"4%","containLabel":true},"series":[{"data":[80,92,90,93,129,133,132,42,53,90]')
|| TO_CLOB(q'[,93,129],"type":"line","color":"#00008B"}],"tooltip":{"trigger":"axis","axisPointer":{"type":"line"}}}]'), EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,17,'DIGITAL ACQUISITION AMG GRAPH','GRAPH_LINES',TO_CLOB(q'[{"xAxis":{"type":"category","data":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"axisLabel":{"margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisTick":{"show":false}},"yAxis":{"type":"value","axisLabel":{"margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisLine":{"show":false},"axisTick":{"show":false},"splitLine":{"lineStyle":{"type":"dotted"}}},"grid":{"left":"3%","right":"4%","containLabel":true},"series":[{"data":[40,102,80,93,12,123,112,32,53,90]')
|| TO_CLOB(q'[,93,59],"type":"line","color":"#00008B"}],"tooltip":{"trigger":"axis","axisPointer":{"type":"line"}}}]'), EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,18,'DIGITAL ACQUISITION CIB GRAPH','GRAPH_LINES',TO_CLOB(q'[{"xAxis":{"type":"category","data":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"axisLabel":{"margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisTick":{"show":false}},"yAxis":{"type":"value","axisLabel":{"margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisLine":{"show":false},"axisTick":{"show":false},"splitLine":{"lineStyle":{"type":"dotted"}}},"grid":{"left":"3%","right":"4%","containLabel":true},"series":[{"data":[80,92,90,93,19,133,102,42,53,90,]')
|| TO_CLOB(q'[93,12],"type":"line","color":"#00008B"}],"tooltip":{"trigger":"axis","axisPointer":{"type":"line"}}}]'), EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,19,'BRAND HEALTH PANEL','PANEL','{ "Title": "Brand Health" }', EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,20,'BRAND HEALTH GRAPH','GRAPH_LINES',TO_CLOB(q'[{"tooltip":{"trigger":"axis","axisPointer":{"type":"line"}},"legend":{"data":[{"name":"Unaided awareness","icon":"line"},{"name":"Aided awareness","icon":"line"},{"name":"Consideration","icon":"line"},{"name":"Unaided Target","icon":"path://M140-440q-25 0-42.5-17.5T80-500q0-25 17.5-42.5T140-560h240q25 0 42.5 17.5T440-500q0 25-17.5 42.5T380-440H140Zm440 0q-25 0-42.5-17.5T520-500q0-25 17.5-42.5T580-560h240q25 0 42.5 17.5T880-500q0 25-17.5 42.5T820-440H580Z"},{"name":"Aided Target","icon":"path://M]')
|| TO_CLOB(q'[140-440q-25 0-42.5-17.5T80-500q0-25 17.5-42.5T140-560h240q25 0 42.5 17.5T440-500q0 25-17.5 42.5T380-440H140Zm440 0q-25 0-42.5-17.5T520-500q0-25 17.5-42.5T580-560h240q25 0 42.5 17.5T880-500q0 25-17.5 42.5T820-440H580Z"},{"name":"Consideration Target","icon":"path://M140-440q-25 0-42.5-17.5T80-500q0-25 17.5-42.5T140-560h240q25 0 42.5 17.5T440-500q0 25-17.5 42.5T380-440H140Zm440 0q-25 0-42.5-17.5T520-500q0-25 17.5-42.5T580-560h240q25 0 42.5 17.5T880-500q0 25-17.5 42.5T820-440H580Z"}],"bottom":350,"]')
|| TO_CLOB(q'[textStyle":{"fontSize":18},"width":600},"grid":{"top":"10%","left":"0%","right":"4%","containLabel":true},"xAxis":{"type":"category","boundaryGap":false,"data":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"axisLabel":{"margin":15,"textStyle":{"fontSize":14}},"axisTick":{"show":false}},"yAxis":{"type":"value","axisLabel":{"formatter":"{value}%","margin":15,"textStyle":{"fontSize":14}},"axisLine":{"show":false},"axisTick":{"show":false},"splitLine":{"lineStyle":{"type"]')
|| TO_CLOB(q'[:"dotted"}}},"series":[{"name":"Unaided awareness","type":"line","data":[20,32,41,34,50,60,65,20,32,41,34,50,60,67]},{"name":"Aided awareness","type":"line","data":[30,42,51,44,60,67,68,30,42,51,44,60,63,59]},{"name":"Consideration","type":"line","data":[20,52,61,54,65,50,30,20,52,61,54,65,40,60]},{"name":"Unaided Target","type":"line","symbol":"none","markLine":{"data":[{"yAxis":70}]},"lineStyle":{"normal":{"type":"dotted"}}},{"name":"Aided Target","type":"line","symbol":"none","markLine":{"dat]')
|| TO_CLOB(q'[a":[{"yAxis":50}]},"lineStyle":{"normal":{"type":"dotted"}}},{"name":"Consideration Target","type":"line","symbol":"none","markLine":{"data":[{"yAxis":30}]},"lineStyle":{"normal":{"type":"dotted"}}}]}]'), EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,21,'CLIENT LOYALTY PANEL','PANEL','{ "Title": "Client Loyalty" }', EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,22,'CLIENT LOYALTY TABS','TABS','{ "TAB_LIST": [ { "COMP_ID": "23", "NAME": "Retail" }, { "COMP_ID": "24", "NAME": "AMG" }, { "COMP_ID": "25", "NAME": "C&IB" } ] }', EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,23,'CLIENT LOYALTY RETAIL CARD','KPI_CARD','{"CARD_HEADER":"Retail","KPIS":[{"KPI_LBL":"Engagement","KPI_VALUE":"73%","KPI_PERC_CHANGE":"3%","KPI_PERC_CHANGE_ICON":"arrow_upward","KPI_LBL_POSTFIX":"YTD","KPI_ID":"39"},{"KPI_LBL":"Retention","KPI_VALUE":"89%","KPI_PERC_CHANGE":"6%","KPI_PERC_CHANGE_ICON":"arrow_upward","KPI_LBL_POSTFIX":"YTD","KPI_ID":"40"}]}', EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,24,'CLIENT LOYALTY RETAIL AMG CARD','KPI_CARD','{"CARD_HEADER":"Retail","KPIS":[{"KPI_LBL":"Engagement","KPI_VALUE":"52%","KPI_PERC_CHANGE":"1.3%","KPI_PERC_CHANGE_ICON":"arrow_upward","KPI_LBL_POSTFIX":"YTD","KPI_ID":"41"},{"KPI_LBL":"Retention","KPI_VALUE":"92%","KPI_PERC_CHANGE":"2.1%","KPI_PERC_CHANGE_ICON":"arrow_upward","KPI_LBL_POSTFIX":"YTD","KPI_ID":"42"}]}', EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,25,'CLIENT LOYALTY RETAIL CIB CARD','KPI_CARD','{"CARD_HEADER":"Retail","KPIS":[{"KPI_LBL":"Engagement","KPI_VALUE":"62%","KPI_PERC_CHANGE":"1%","KPI_PERC_CHANGE_ICON":"arrow_upward","KPI_LBL_POSTFIX":"YTD","KPI_ID":"43"},{"KPI_LBL":"Retention","KPI_VALUE":"96%","KPI_PERC_CHANGE":"5%","KPI_PERC_CHANGE_ICON":"arrow_upward","KPI_LBL_POSTFIX":"YTD","KPI_ID":"44"}]}', EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,26,'CLV MODAL GRAPH','GRAPH',TO_CLOB(q'[{"xAxis":{"type":"category","boundaryGap":false,"data":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"axisLabel":{"margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisTick":{"show":false}},"yAxis":{"type":"value","axisLabel":{"formatter":"${value}M","margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisLine":{"show":false},"axisTick":{"show":false},"splitLine":{"lineStyle":{"type":"dotted"}}},"grid":{"top":"7%","left":"2%","right":"4%","bottom":"40%","c]')
|| TO_CLOB(q'[ontainLabel":true},"tooltip":{"trigger":"axis","axisPointer":{"type":"line"}},"series":{"data":[9,12,13,9,12,15,9,12,13,9,12,15],"type":"line","areaStyle":{},"smooth":true},"areaStyle":{"color":{"type":"linear","x":0,"y":0,"x2":0,"y2":1,"colorStops":[{"offset":0,"color":"rgba(255, 0, 0, 0.7)"},{"offset":1,"color":"rgba(255, 0, 0, 0)"}],"global":false}}}]'), EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,27,'CLV MODAL TOTAL RETAIL CUST GRAPH','GRAPH',TO_CLOB(q'[{"xAxis":{"type":"category","boundaryGap":false,"data":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"axisLabel":{"margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisTick":{"show":false}},"yAxis":{"type":"value","axisLabel":{"formatter":"${value}M","margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisLine":{"show":false},"axisTick":{"show":false},"splitLine":{"lineStyle":{"type":"dotted"}}},"grid":{"top":"7%","left":"2%","right":"4%","bottom":"40%","c]')
|| TO_CLOB(q'[ontainLabel":true},"tooltip":{"trigger":"axis","axisPointer":{"type":"line"}},"series":{"data":[9,10,8,15,11,15,9,10,13,9,12,15],"type":"line","areaStyle":{},"smooth":true},"areaStyle":{"color":{"type":"linear","x":0,"y":0,"x2":0,"y2":1,"colorStops":[{"offset":0,"color":"rgba(255, 0, 0, 0.7)"},{"offset":1,"color":"rgba(255, 0, 0, 0)"}],"global":false}}}]'), EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,28,'CLV MODAL NEW RETAIL CUST GRAPH','GRAPH',TO_CLOB(q'[{"xAxis":{"type":"category","boundaryGap":false,"data":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"axisLabel":{"margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisTick":{"show":false}},"yAxis":{"type":"value","axisLabel":{"formatter":"${value}M","margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisLine":{"show":false},"axisTick":{"show":false},"splitLine":{"lineStyle":{"type":"dotted"}}},"grid":{"top":"7%","left":"2%","right":"4%","bottom":"40%","c]')
|| TO_CLOB(q'[ontainLabel":true},"tooltip":{"trigger":"axis","axisPointer":{"type":"line"}},"series":{"data":[9,10,15,15,8,15,9,10,8,9,12,13],"type":"line","areaStyle":{},"smooth":true},"areaStyle":{"color":{"type":"linear","x":0,"y":0,"x2":0,"y2":1,"colorStops":[{"offset":0,"color":"rgba(255, 0, 0, 0.7)"},{"offset":1,"color":"rgba(255, 0, 0, 0)"}],"global":false}}}]'), EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,29,'CLV MODAL CROSS RETAIL CUST GRAPH','GRAPH',TO_CLOB(q'[{"xAxis":{"type":"category","boundaryGap":false,"data":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"axisLabel":{"margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisTick":{"show":false}},"yAxis":{"type":"value","axisLabel":{"formatter":"${value}M","margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisLine":{"show":false},"axisTick":{"show":false},"splitLine":{"lineStyle":{"type":"dotted"}}},"grid":{"top":"7%","left":"2%","right":"4%","bottom":"40%","c]')
|| TO_CLOB(q'[ontainLabel":true},"tooltip":{"trigger":"axis","axisPointer":{"type":"line"}},"series":{"data":[12,15,10,15,8,10,9,10,8,9,15,13],"type":"line","areaStyle":{},"smooth":true},"areaStyle":{"color":{"type":"linear","x":0,"y":0,"x2":0,"y2":1,"colorStops":[{"offset":0,"color":"rgba(255, 0, 0, 0.7)"},{"offset":1,"color":"rgba(255, 0, 0, 0)"}],"global":false}}}]'), EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,30,'CLV MODAL TOTAL AMG CUST GRAPH','GRAPH',TO_CLOB(q'[{"xAxis":{"type":"category","boundaryGap":false,"data":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"axisLabel":{"margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisTick":{"show":false}},"yAxis":{"type":"value","axisLabel":{"formatter":"${value}M","margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisLine":{"show":false},"axisTick":{"show":false},"splitLine":{"lineStyle":{"type":"dotted"}}},"grid":{"top":"7%","left":"2%","right":"4%","bottom":"40%","c]')
|| TO_CLOB(q'[ontainLabel":true},"tooltip":{"trigger":"axis","axisPointer":{"type":"line"}},"series":{"data":[10,9,12,15,8,10,9,10,8,9,13,10],"type":"line","areaStyle":{},"smooth":true},"areaStyle":{"color":{"type":"linear","x":0,"y":0,"x2":0,"y2":1,"colorStops":[{"offset":0,"color":"rgba(255, 0, 0, 0.7)"},{"offset":1,"color":"rgba(255, 0, 0, 0)"}],"global":false}}}]'), EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,31,'CLV MODAL NEW AMG CUST GRAPH','GRAPH',TO_CLOB(q'[{"xAxis":{"type":"category","boundaryGap":false,"data":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"axisLabel":{"margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisTick":{"show":false}},"yAxis":{"type":"value","axisLabel":{"formatter":"${value}M","margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisLine":{"show":false},"axisTick":{"show":false},"splitLine":{"lineStyle":{"type":"dotted"}}},"grid":{"top":"7%","left":"2%","right":"4%","bottom":"40%","c]')
|| TO_CLOB(q'[ontainLabel":true},"tooltip":{"trigger":"axis","axisPointer":{"type":"line"}},"series":{"data":[5,9,10,13,10,9,9,10,8,12,13,10],"type":"line","areaStyle":{},"smooth":true},"areaStyle":{"color":{"type":"linear","x":0,"y":0,"x2":0,"y2":1,"colorStops":[{"offset":0,"color":"rgba(255, 0, 0, 0.7)"},{"offset":1,"color":"rgba(255, 0, 0, 0)"}],"global":false}}}]'), EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,32,'CLV MODAL CROSS AMG CUST GRAPH','GRAPH',TO_CLOB(q'[{"xAxis":{"type":"category","boundaryGap":false,"data":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"axisLabel":{"margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisTick":{"show":false}},"yAxis":{"type":"value","axisLabel":{"formatter":"${value}M","margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisLine":{"show":false},"axisTick":{"show":false},"splitLine":{"lineStyle":{"type":"dotted"}}},"grid":{"top":"7%","left":"2%","right":"4%","bottom":"40%","c]')
|| TO_CLOB(q'[ontainLabel":true},"tooltip":{"trigger":"axis","axisPointer":{"type":"line"}},"series":{"data":[10,9,12,13,10,13,9,10,8,12,9,10],"type":"line","areaStyle":{},"smooth":true},"areaStyle":{"color":{"type":"linear","x":0,"y":0,"x2":0,"y2":1,"colorStops":[{"offset":0,"color":"rgba(255, 0, 0, 0.7)"},{"offset":1,"color":"rgba(255, 0, 0, 0)"}],"global":false}}}]'), EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,33,'CLV MODAL TOTAL C&IB CUST GRAPH','GRAPH',TO_CLOB(q'[{"xAxis":{"type":"category","boundaryGap":false,"data":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"axisLabel":{"margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisTick":{"show":false}},"yAxis":{"type":"value","axisLabel":{"formatter":"${value}M","margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisLine":{"show":false},"axisTick":{"show":false},"splitLine":{"lineStyle":{"type":"dotted"}}},"grid":{"top":"7%","left":"2%","right":"4%","bottom":"40%","c]')
|| TO_CLOB(q'[ontainLabel":true},"tooltip":{"trigger":"axis","axisPointer":{"type":"line"}},"series":{"data":[12,9,12,13,12,13,12,10,8,13,9,10],"type":"line","areaStyle":{},"smooth":true},"areaStyle":{"color":{"type":"linear","x":0,"y":0,"x2":0,"y2":1,"colorStops":[{"offset":0,"color":"rgba(255, 0, 0, 0.7)"},{"offset":1,"color":"rgba(255, 0, 0, 0)"}],"global":false}}}]'), EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,34,'CLV MODAL NEW C&IB CUST GRAPH','GRAPH',TO_CLOB(q'[{"xAxis":{"type":"category","boundaryGap":false,"data":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"axisLabel":{"margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisTick":{"show":false}},"yAxis":{"type":"value","axisLabel":{"formatter":"${value}M","margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisLine":{"show":false},"axisTick":{"show":false},"splitLine":{"lineStyle":{"type":"dotted"}}},"grid":{"top":"7%","left":"2%","right":"4%","bottom":"40%","c]')
|| TO_CLOB(q'[ontainLabel":true},"tooltip":{"trigger":"axis","axisPointer":{"type":"line"}},"series":{"data":[9,9,5,13,14,13,12,10,8,10,9,14],"type":"line","areaStyle":{},"smooth":true},"areaStyle":{"color":{"type":"linear","x":0,"y":0,"x2":0,"y2":1,"colorStops":[{"offset":0,"color":"rgba(255, 0, 0, 0.7)"},{"offset":1,"color":"rgba(255, 0, 0, 0)"}],"global":false}}}]'), EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,35,'CLV MODAL CROSS C&IB CUST GRAPH','GRAPH',TO_CLOB(q'[{"xAxis":{"type":"category","boundaryGap":false,"data":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"axisLabel":{"margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisTick":{"show":false}},"yAxis":{"type":"value","axisLabel":{"formatter":"${value}M","margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisLine":{"show":false},"axisTick":{"show":false},"splitLine":{"lineStyle":{"type":"dotted"}}},"grid":{"top":"7%","left":"2%","right":"4%","bottom":"40%","c]')
|| TO_CLOB(q'[ontainLabel":true},"tooltip":{"trigger":"axis","axisPointer":{"type":"line"}},"series":{"data":[7,12,15,6,14,13,12,10,8,14,9,14],"type":"line","areaStyle":{},"smooth":true},"areaStyle":{"color":{"type":"linear","x":0,"y":0,"x2":0,"y2":1,"colorStops":[{"offset":0,"color":"rgba(255, 0, 0, 0.7)"},{"offset":1,"color":"rgba(255, 0, 0, 0)"}],"global":false}}}]'), EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,36,'MARKETING SPEND MODAL RETAIL GRAPH','GRAPH',TO_CLOB(q'[{"xAxis":{"type":"category","boundaryGap":false,"data":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"axisLabel":{"margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisTick":{"show":false}},"yAxis":{"type":"value","axisLabel":{"formatter":"${value}M","margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisLine":{"show":false},"axisTick":{"show":false},"splitLine":{"lineStyle":{"type":"dotted"}}},"grid":{"top":"7%","left":"2%","right":"4%","bottom":"40%","c]')
|| TO_CLOB(q'[ontainLabel":true},"tooltip":{"trigger":"axis","axisPointer":{"type":"line"}},"series":{"data":[10,13,10,6,14,13,10,13,8,12,9,10],"type":"line","areaStyle":{},"smooth":true},"areaStyle":{"color":{"type":"linear","x":0,"y":0,"x2":0,"y2":1,"colorStops":[{"offset":0,"color":"rgba(255, 0, 0, 0.7)"},{"offset":1,"color":"rgba(255, 0, 0, 0)"}],"global":false}}}]'), EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,37,'MARKETING SPEND MODAL AMG GRAPH','GRAPH',TO_CLOB(q'[{"xAxis":{"type":"category","boundaryGap":false,"data":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"axisLabel":{"margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisTick":{"show":false}},"yAxis":{"type":"value","axisLabel":{"formatter":"${value}M","margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisLine":{"show":false},"axisTick":{"show":false},"splitLine":{"lineStyle":{"type":"dotted"}}},"grid":{"top":"7%","left":"2%","right":"4%","bottom":"40%","c]')
|| TO_CLOB(q'[ontainLabel":true},"tooltip":{"trigger":"axis","axisPointer":{"type":"line"}},"series":{"data":[10,13,10,12,14,10,10,13,12,10,9,10],"type":"line","areaStyle":{},"smooth":true},"areaStyle":{"color":{"type":"linear","x":0,"y":0,"x2":0,"y2":1,"colorStops":[{"offset":0,"color":"rgba(255, 0, 0, 0.7)"},{"offset":1,"color":"rgba(255, 0, 0, 0)"}],"global":false}}}]'), EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,38,'MARKETING SPEND MODAL C&IB GRAPH','GRAPH',TO_CLOB(q'[{"xAxis":{"type":"category","boundaryGap":false,"data":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"axisLabel":{"margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisTick":{"show":false}},"yAxis":{"type":"value","axisLabel":{"formatter":"${value}M","margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisLine":{"show":false},"axisTick":{"show":false},"splitLine":{"lineStyle":{"type":"dotted"}}},"grid":{"top":"7%","left":"2%","right":"4%","bottom":"40%","c]')
|| TO_CLOB(q'[ontainLabel":true},"tooltip":{"trigger":"axis","axisPointer":{"type":"line"}},"series":{"data":[10,13,6,12,14,10,10,5,15,10,9,8],"type":"line","areaStyle":{},"smooth":true},"areaStyle":{"color":{"type":"linear","x":0,"y":0,"x2":0,"y2":1,"colorStops":[{"offset":0,"color":"rgba(255, 0, 0, 0.7)"},{"offset":1,"color":"rgba(255, 0, 0, 0)"}],"global":false}}}]'), EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,39,'CLIENT LOYALTY MODAL RETAIL ENGAGEMENT GRAPH','GRAPH',TO_CLOB(q'[{"xAxis":{"type":"category","boundaryGap":false,"data":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"axisLabel":{"margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisTick":{"show":false}},"yAxis":{"type":"value","axisLabel":{"formatter":"${value}M","margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisLine":{"show":false},"axisTick":{"show":false},"splitLine":{"lineStyle":{"type":"dotted"}}},"grid":{"top":"7%","left":"2%","right":"4%","bottom":"40%","c]')
|| TO_CLOB(q'[ontainLabel":true},"tooltip":{"trigger":"axis","axisPointer":{"type":"line"}},"series":{"data":[3,15,6,12,14,10,10,15,12,10,19,8],"type":"line","areaStyle":{},"smooth":true},"areaStyle":{"color":{"type":"linear","x":0,"y":0,"x2":0,"y2":1,"colorStops":[{"offset":0,"color":"rgba(255, 0, 0, 0.7)"},{"offset":1,"color":"rgba(255, 0, 0, 0)"}],"global":false}}}]'), EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,40,'CLIENT LOYALTY MODAL RETAIL RETENTION GRAPH','GRAPH',TO_CLOB(q'[{"xAxis":{"type":"category","boundaryGap":false,"data":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"axisLabel":{"margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisTick":{"show":false}},"yAxis":{"type":"value","axisLabel":{"formatter":"${value}M","margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisLine":{"show":false},"axisTick":{"show":false},"splitLine":{"lineStyle":{"type":"dotted"}}},"grid":{"top":"7%","left":"2%","right":"4%","bottom":"40%","c]')
|| TO_CLOB(q'[ontainLabel":true},"tooltip":{"trigger":"axis","axisPointer":{"type":"line"}},"series":{"data":[3,12,16,12,14,10,12,15,12,10,19,8],"type":"line","areaStyle":{},"smooth":true},"areaStyle":{"color":{"type":"linear","x":0,"y":0,"x2":0,"y2":1,"colorStops":[{"offset":0,"color":"rgba(255, 0, 0, 0.7)"},{"offset":1,"color":"rgba(255, 0, 0, 0)"}],"global":false}}}]'), EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,41,'CLIENT LOYALTY MODAL AMG ENGAGEMENT GRAPH','GRAPH',TO_CLOB(q'[{"xAxis":{"type":"category","boundaryGap":false,"data":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"axisLabel":{"margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisTick":{"show":false}},"yAxis":{"type":"value","axisLabel":{"formatter":"${value}M","margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisLine":{"show":false},"axisTick":{"show":false},"splitLine":{"lineStyle":{"type":"dotted"}}},"grid":{"top":"7%","left":"2%","right":"4%","bottom":"40%","c]')
|| TO_CLOB(q'[ontainLabel":true},"tooltip":{"trigger":"axis","axisPointer":{"type":"line"}},"series":{"data":[3,12,12,12,14,14,12,15,12,10,11,8],"type":"line","areaStyle":{},"smooth":true},"areaStyle":{"color":{"type":"linear","x":0,"y":0,"x2":0,"y2":1,"colorStops":[{"offset":0,"color":"rgba(255, 0, 0, 0.7)"},{"offset":1,"color":"rgba(255, 0, 0, 0)"}],"global":false}}}]'), EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,42,'CLIENT LOYALTY MODAL AMG RETENTION GRAPH','GRAPH',TO_CLOB(q'[{"xAxis":{"type":"category","boundaryGap":false,"data":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"axisLabel":{"margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisTick":{"show":false}},"yAxis":{"type":"value","axisLabel":{"formatter":"${value}M","margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisLine":{"show":false},"axisTick":{"show":false},"splitLine":{"lineStyle":{"type":"dotted"}}},"grid":{"top":"7%","left":"2%","right":"4%","bottom":"40%","c]')
|| TO_CLOB(q'[ontainLabel":true},"tooltip":{"trigger":"axis","axisPointer":{"type":"line"}},"series":{"data":[3,12,4,14,12,14,12,15,14,10,11,8],"type":"line","areaStyle":{},"smooth":true},"areaStyle":{"color":{"type":"linear","x":0,"y":0,"x2":0,"y2":1,"colorStops":[{"offset":0,"color":"rgba(255, 0, 0, 0.7)"},{"offset":1,"color":"rgba(255, 0, 0, 0)"}],"global":false}}}]'), EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,43,'CLIENT LOYALTY MODAL C&IB ENGAGEMENT GRAPH','GRAPH',TO_CLOB(q'[{"xAxis":{"type":"category","boundaryGap":false,"data":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"axisLabel":{"margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisTick":{"show":false}},"yAxis":{"type":"value","axisLabel":{"formatter":"${value}M","margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisLine":{"show":false},"axisTick":{"show":false},"splitLine":{"lineStyle":{"type":"dotted"}}},"grid":{"top":"7%","left":"2%","right":"4%","bottom":"40%","c]')
|| TO_CLOB(q'[ontainLabel":true},"tooltip":{"trigger":"axis","axisPointer":{"type":"line"}},"series":{"data":[3,12,4,10,12,14,12,10,11,14,11,8],"type":"line","areaStyle":{},"smooth":true},"areaStyle":{"color":{"type":"linear","x":0,"y":0,"x2":0,"y2":1,"colorStops":[{"offset":0,"color":"rgba(255, 0, 0, 0.7)"},{"offset":1,"color":"rgba(255, 0, 0, 0)"}],"global":false}}}]'), EMPTY_CLOB(),null,null,null,null,'Y');
Insert into dashboard_demo_schema.dashboard_components (DASH_ID,COMP_ID,COMP_NAME,COMP_TYPE,COMP_DATA,COMP_DATA_QUERY,COMP_PARENT,COMP_ROW,COMP_COL_SPAN,DISPLAY_ORDER,IS_ACTIVE) values (1,44,'CLIENT LOYALTY MODAL C&IB RETENTION GRAPH','GRAPH',TO_CLOB(q'[{"xAxis":{"type":"category","boundaryGap":false,"data":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"axisLabel":{"margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisTick":{"show":false}},"yAxis":{"type":"value","axisLabel":{"formatter":"${value}M","margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisLine":{"show":false},"axisTick":{"show":false},"splitLine":{"lineStyle":{"type":"dotted"}}},"grid":{"top":"7%","left":"2%","right":"4%","bottom":"40%","c]')
|| TO_CLOB(q'[ontainLabel":true},"tooltip":{"trigger":"axis","axisPointer":{"type":"line"}},"series":{"data":[3,12,6,12,12,10,12,10,16,14,11,8],"type":"line","areaStyle":{},"smooth":true},"areaStyle":{"color":{"type":"linear","x":0,"y":0,"x2":0,"y2":1,"colorStops":[{"offset":0,"color":"rgba(255, 0, 0, 0.7)"},{"offset":1,"color":"rgba(255, 0, 0, 0)"}],"global":false}}}]'), EMPTY_CLOB(),null,null,null,null,'Y');


--DML FOR table dashboard_master

Insert into dashboard_demo_schema.dashboard_master (DASH_ID,DASH_NAME,DASH_TITLE,MENU,MENU_GROUP,IS_ACTIVE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) values (1,'MARKETING DASHBOARD','Excutive Marketing Dashboard','\main\KPI\dash1','KPI MANAGER','Y','satwik.rastogi',to_timestamp('30-04-24 6:32:08.310595000 AM','DD-MM-RR fmHH12:fmMI:SSXFF AM'),'satwik.rastogi',to_timestamp('30-04-24 6:32:08.310595000 AM','DD-MM-RR fmHH12:fmMI:SSXFF AM'));

--DML FOR table component_master

Insert into dashboard_demo_schema.component_master (COMP_TYPE_ID,COMP_TYPE_NAME,COMP_DESC,HTML_TEMPLATE,DATA_TEMPLATE,IS_ACTIVE) values (1,'KPI_CARD','KPI Cards','NA','{"CARD_HEADER":"CLV","KPIS":[{"KPI_LBL":"Total Customers","KPI_LBL_POSTFIX":"YTD","KPI_PERC_CHANGE":"5%","KPI_PERC_CHANGE_ICON":"?","KPI_VALUE":"$10M"}]}','Y');
Insert into dashboard_demo_schema.component_master (COMP_TYPE_ID,COMP_TYPE_NAME,COMP_DESC,HTML_TEMPLATE,DATA_TEMPLATE,IS_ACTIVE) values (2,'TAB','Tabs','NA','{ "TAB_LIST":[{"NAME":"", "ITEMS":"[]" }  ]  }','Y');
Insert into dashboard_demo_schema.component_master (COMP_TYPE_ID,COMP_TYPE_NAME,COMP_DESC,HTML_TEMPLATE,DATA_TEMPLATE,IS_ACTIVE) values (3,'TOGGLE','Toggle','NA','{ "NAME":"", "VALUE_ON":"", "VALUE_OFF":""  }','Y');
Insert into dashboard_demo_schema.component_master (COMP_TYPE_ID,COMP_TYPE_NAME,COMP_DESC,HTML_TEMPLATE,DATA_TEMPLATE,IS_ACTIVE) values (4,'PANEL','Panels','NA','{"NAME":"", "ITEMS":"[]" } ]  ','Y');
Insert into dashboard_demo_schema.component_master (COMP_TYPE_ID,COMP_TYPE_NAME,COMP_DESC,HTML_TEMPLATE,DATA_TEMPLATE,IS_ACTIVE) values (5,'GRAPH','Graphs','NA',TO_CLOB(q'[{"xAxis":{"type":"category","data":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"axisLabel":{"margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisTick":{"show":false}},"yAxis":{"type":"value","axisLabel":{"margin":15,"textStyle":{"fontSize":14,"color":"grey"}},"axisLine":{"show":false},"axisTick":{"show":false},"splitLine":{"lineStyle":{"type":"dotted"}}},"grid":{"left":"3%","right":"4%","containLabel":true},"series":[{"data":[80,92,90,93,129,133,132,42,53,90]')
|| TO_CLOB(q'[,93,129],"type":"line","color":"#00008B"}],"tooltip":{"trigger":"axis","axisPointer":{"type":"line"}}}]'),'Y');